import { StyleSheet } from "react-native";
import { COLORS } from "../utils/constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  mapContainer: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  topButtonsContainer: {
    position: "absolute",
    top: 48,
    left: 16,
    right: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    zIndex: 20,
  },
  coloredButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
    marginHorizontal: 4,
  },
  mapToggleContainer: {
    position: "relative",
  },
  legendContainer: {
    position: "relative",
  },
  legendDropdown: {
    position: "absolute",
    top: 52,
    left: 0,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    minWidth: 180,
  },
  legendDropdownTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.TEXT_PRIMARY,
    marginBottom: 8,
    textAlign: "center",
  },
  legendDropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  legendDropdownText: {
    fontSize: 12,
    color: COLORS.TEXT_SECONDARY,
    marginLeft: 8,
    flex: 1,
  },
  mapTypeSelector: {
    position: "absolute",
    top: 52,
    right: 0,
    flexDirection: "column",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    minWidth: 100,
  },
  mapTypeButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  mapTypeButtonActive: {
    backgroundColor: COLORS.PRIMARY,
  },
  mapTypeButtonText: {
    fontSize: 12,
    color: COLORS.TEXT_SECONDARY,
    fontWeight: "600",
  },
  mapTypeButtonTextActive: {
    color: COLORS.WHITE,
  },
  refreshButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.WHITE,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
  },
  refreshButtonText: {
    fontSize: 12,
    color: COLORS.TEXT_SECONDARY,
  },
  markerTitle: {
    fontWeight: "700",
    color: COLORS.TEXT_PRIMARY,
    fontSize: 12,
  },
  markerSubtitle: {
    fontSize: 10,
    color: COLORS.TEXT_SECONDARY,
  },
  markerContainer: {
    padding: 10,
    width: 220,
    backgroundColor: COLORS.WHITE,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  markerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  markerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  markerValue: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.TEXT_PRIMARY,
  },
  markerBadge: {
    minWidth: 48,
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: COLORS.PRIMARY,
    alignItems: "center",
  },
  markerBadgeText: {
    fontSize: 10,
    color: COLORS.WHITE,
    fontWeight: "700",
  },
  bottomSheetContent: {
    padding: 16,
    backgroundColor: COLORS.BACKGROUND,
  },
  bottomSheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  bottomSheetTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.TEXT_PRIMARY,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerRefreshButton: {
    padding: 4,
  },
  nearbyStationCard: {
    marginBottom: 12,
    backgroundColor: COLORS.WHITE,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    padding: 14,
  },
  nearbyStationTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.TEXT_PRIMARY,
    marginBottom: 4,
  },
  nearbyStationSubtitle: {
    fontSize: 13,
    color: COLORS.TEXT_SECONDARY,
  },
  nearbyStationStatus: {
    marginTop: 10,
    color: COLORS.TEXT_PRIMARY,
    fontWeight: "600",
  },
  nearbyStationInfo: {
    marginTop: 6,
    color: COLORS.TEXT_SECONDARY,
    fontSize: 12,
  },
  bottomActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  bottomSheetButton: {
    flex: 1,
    marginRight: 8,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: COLORS.PRIMARY,
  },
  bottomSheetButtonText: {
    color: COLORS.WHITE,
    fontWeight: "700",
  },
  fabContainer: {
    position: "absolute",
    bottom: 32,
    right: 24,
    alignItems: "flex-end",
  },
  fab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.PRIMARY,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 12,
  },
  fabOption: {
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  fabOptionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 24,
    minWidth: 140,
    justifyContent: "flex-start",
  },
  fabOptionText: {
    marginLeft: 12,
    fontSize: 14,
    color: COLORS.WHITE,
    fontWeight: "600",
  },
  indicatorDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.SECONDARY,
    marginRight: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.BACKGROUND_LIGHT,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#666",
  },
  infoContainer: {
    position: "absolute",
    top: 130,
    left: 16,
    backgroundColor: COLORS.BACKGROUND_WHITE,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 900,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
  },
  infoText: {
    fontSize: 10,
    color: "#666",
    marginLeft: 4,
  },
  statsContainer: {
    position: "absolute",
    bottom: 100,
    left: 16,
    backgroundColor: "rgba(0,0,0,0.75)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    zIndex: 900,
  },
  statsText: {
    color: COLORS.BACKGROUND_WHITE,
    fontSize: 11,
    fontWeight: "500",
  },
});
